# Generated by Django 4.0.2 on 2022-02-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('wall_id', models.IntegerField()),
                ('text', models.CharField(max_length=3000)),
                ('pictures', models.FileField(upload_to='')),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
