# Generated by Django 4.0.3 on 2022-03-07 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_novelty_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelty',
            name='pictures',
        ),
        migrations.AddField(
            model_name='novelty',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
