# Generated by Django 4.0.3 on 2022-03-08 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_remove_novelty_pictures_novelty_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelty',
            name='wall_id',
        ),
        migrations.AddField(
            model_name='novelty',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.community'),
        ),
        migrations.AlterField(
            model_name='novelty',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='novelty',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
