# Generated by Django 4.0.3 on 2022-03-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_novelty_wall_id_novelty_group_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novelty',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='novelty',
            old_name='user_id',
            new_name='sender',
        ),
    ]
