# Generated by Django 4.0.3 on 2022-03-13 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_group_id_novelty_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelty',
            name='name_new',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
