# Generated by Django 4.0.3 on 2022-03-26 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_novelty_name_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelty',
            name='title_picture',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novelty',
            name='picture',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
