# Generated by Django 4.0.3 on 2022-03-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_novelty_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelty',
            name='title_picture',
        ),
    ]
