# Generated by Django 4.0.3 on 2022-04-02 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0009_remove_novelty_title_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelty',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/images/users/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='NoveltyLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='like')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('liked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('novelty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.novelty')),
            ],
        ),
    ]
