# Generated by Django 4.0.3 on 2022-04-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_novelty_picture_noveltylikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelty',
            name='likes',
        ),
    ]
