# Generated by Django 4.0.4 on 2022-05-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_remove_noveltylikes_created_novelty_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelty',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/images/novelty/%Y/%m/%d/'),
        ),
    ]
