# Generated by Django 4.0.4 on 2022-05-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_novelty_picture'),
        ('news', '0014_alter_novelty_sender'),
    ]

    operations = [
    ]
