# Generated by Django 4.0.4 on 2022-05-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_merge_20220504_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noveltylikes',
            name='like',
        ),
    ]
