# Generated by Django 4.0.3 on 2022-04-13 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
