# Generated by Django 4.0.3 on 2022-04-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_existenceingroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='existenceingroup',
            name='is_existed',
            field=models.BooleanField(default=False),
        ),
    ]
