# Generated by Django 4.0.2 on 2022-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_remove_existenceingroup_is_existed'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='icon',
            field=models.ImageField(default='No image', upload_to='community_icons'),
            preserve_default=False,
        ),
    ]
