# Generated by Django 4.0.4 on 2022-04-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_alter_community_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='icon',
        ),
    ]
