# Generated by Django 4.0.4 on 2022-04-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_remove_community_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='icon',
            field=models.ImageField(default='static/images/community_icons/no_img.png', upload_to='static/images/community_icons/%Y/%m/%d/'),
        ),
    ]
