# Generated by Django 4.0.4 on 2022-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='static\\images\\avatars\\base.png', upload_to='static/images/avatars/%Y/%m/%d/')),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('other_socnet', models.CharField(blank=True, max_length=300, null=True)),
                ('career', models.CharField(blank=True, max_length=300, null=True)),
                ('interests', models.CharField(blank=True, max_length=300, null=True)),
                ('favorite_musics', models.CharField(blank=True, max_length=300, null=True)),
                ('favorite_movies', models.CharField(blank=True, max_length=300, null=True)),
                ('favorite_TVshows', models.CharField(blank=True, max_length=300, null=True)),
                ('favorite_books', models.CharField(blank=True, max_length=300, null=True)),
                ('favorite_games', models.CharField(blank=True, max_length=300, null=True)),
                ('favorite_quotes', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('about_me', models.CharField(blank=True, max_length=300, null=True)),
                ('life_position', models.CharField(blank=True, max_length=300, null=True)),
                ('political_preferences', models.CharField(blank=True, max_length=300, null=True)),
                ('world_outlook', models.CharField(blank=True, max_length=300, null=True)),
                ('main_in_life', models.CharField(blank=True, max_length=300, null=True)),
                ('main_in_people', models.CharField(blank=True, max_length=300, null=True)),
                ('attitude_to_smoking', models.CharField(blank=True, max_length=300, null=True)),
                ('attitude_to_alcohol', models.CharField(blank=True, max_length=300, null=True)),
                ('inspires', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
