# Generated by Django 4.0.4 on 2022-05-28 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='images/avatars/base.png', force_format=None, keep_meta=True, quality=50, size=[500, 500], upload_to='images/avatars/%Y/%m/%d/')),
                ('rating', models.IntegerField(default=0)),
                ('img_confirmation', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('Л', 'Любой')], max_length=1, null=True, verbose_name='Пол')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('city', models.CharField(blank=True, max_length=300, null=True, verbose_name='Город')),
                ('other_socnet', models.CharField(blank=True, max_length=300, null=True, verbose_name='Другие соцсети')),
                ('career', models.CharField(blank=True, max_length=300, null=True, verbose_name='Деятельность')),
                ('interests', models.CharField(blank=True, max_length=300, null=True, verbose_name='Интересы')),
                ('favorite_musics', models.CharField(blank=True, max_length=300, null=True, verbose_name='Любимая музыка')),
                ('favorite_movies', models.CharField(blank=True, max_length=300, null=True, verbose_name='Любимые фильмы')),
                ('favorite_TVshows', models.CharField(blank=True, max_length=300, null=True, verbose_name='Любимые шоу')),
                ('favorite_books', models.CharField(blank=True, max_length=300, null=True, verbose_name='Любимые книги')),
                ('favorite_games', models.CharField(blank=True, max_length=300, null=True, verbose_name='Любимые игры')),
                ('favorite_quotes', models.CharField(blank=True, max_length=300, null=True, verbose_name='Любимые цитаты')),
                ('status', models.CharField(blank=True, max_length=300, null=True, verbose_name='Статус')),
                ('about_me', models.CharField(blank=True, max_length=300, null=True, verbose_name='Обо мне')),
                ('life_position', models.CharField(blank=True, max_length=300, null=True, verbose_name='Жизненная позиция')),
                ('political_preferences', models.CharField(blank=True, max_length=300, null=True, verbose_name='Политические предпочтения')),
                ('world_outlook', models.CharField(blank=True, max_length=300, null=True, verbose_name='Мировозрение')),
                ('main_in_life', models.CharField(blank=True, max_length=300, null=True, verbose_name='Главное в жизни')),
                ('main_in_people', models.CharField(blank=True, max_length=300, null=True, verbose_name='Главное в людях')),
                ('attitude_to_smoking', models.CharField(blank=True, max_length=300, null=True, verbose_name='Отношение к алкоголю')),
                ('attitude_to_alcohol', models.CharField(blank=True, max_length=300, null=True, verbose_name='Отношение к курению')),
                ('inspires', models.CharField(blank=True, max_length=300, null=True, verbose_name='Вдохновляют')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
