# Generated by Django 4.0.4 on 2022-05-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_profile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
