# Generated by Django 4.0.4 on 2022-05-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_profile_img_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('Л', 'Любой')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='attitude_to_alcohol',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Отношение к курению'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='attitude_to_smoking',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Отношение к алкоголю'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Деятельность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_TVshows',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Любимые шоу'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_books',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Любимые книги'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_games',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Любимые игры'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_movies',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Любимые фильмы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_musics',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Любимая музыка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_quotes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Любимые цитаты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='inspires',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Вдохновляют'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Интересы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='life_position',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Жизненная позиция'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_in_life',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Главное в жизни'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_in_people',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Главное в людях'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other_socnet',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Другие соцсети'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='political_preferences',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Политические предпочтения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='world_outlook',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Мировозрение'),
        ),
    ]
