# Generated by Django 4.0.4 on 2022-05-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_profile_birthday_profile_gender_and_more'),
        ('user_profile', '0011_alter_profile_img'),
    ]

    operations = [
    ]
