# Generated by Django 4.0.3 on 2022-04-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_chatuser_delete_chat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='creator',
            new_name='user_creator',
        ),
    ]
