# Generated by Django 4.0.4 on 2022-05-13 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_rename_creator_chat_user_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='icons',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_creator',
        ),
    ]
