# Generated by Django 4.0.4 on 2022-05-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_remove_chat_title_chat_user_1_chat_user_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_2',
        ),
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default=' ', max_length=25),
            preserve_default=False,
        ),
    ]
