# Generated by Django 4.0.4 on 2022-05-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_chat_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='chat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatuser', to='messenger.chat'),
        ),
    ]
