# Generated by Django 4.0.4 on 2022-05-14 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0011_alter_chatuser_chat_id_alter_chatuser_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
