# Generated by Django 4.0.4 on 2022-05-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_chat_user_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_creator',
        ),
    ]
