# Generated by Django 4.0.4 on 2022-05-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0013_remove_chat_user_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
