# Generated by Django 4.0.4 on 2022-05-20 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0014_alter_chat_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('icon', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='static\\images\\avatars\\base.png', force_format=None, keep_meta=True, quality=50, size=[500, 500], upload_to='static/images/avatars/%Y/%m/%d/')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('user_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
