# Generated by Django 4.0.4 on 2022-05-23 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0015_groupchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='icon',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='static/images/avatars/base.png', force_format=None, keep_meta=True, quality=50, size=[500, 500], upload_to='static/tmp/'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
