# Generated by Django 4.0.4 on 2022-05-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0014_alter_chat_title'),
        ('messenger', '0016_chat_user1_chat_user2_alter_chat_icon_and_more'),
    ]

    operations = [
    ]
