# Generated by Django 4.0.4 on 2022-05-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0017_merge_20220527_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
