# Generated by Django 4.0.4 on 2022-05-27 21:48

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0018_alter_chat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='icon',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='images/avatars/base.png', force_format=None, keep_meta=True, quality=50, size=[500, 500], upload_to='static/tmp/'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='icon',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='images\\avatars\\base.png', force_format=None, keep_meta=True, quality=50, size=[500, 500], upload_to='images/avatars/%Y/%m/%d/'),
        ),
    ]
